name: reduced_mobx
version: 0.1.0
description: Implementation of the state management API 'reduced' on top of the state management framework 'MobX'.
repository: https://github.com/partmaster/reduced_mobx
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  reduced:
    git:
      url: https://github.com/partmaster/reduced.git
      ref: main
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
