name: counter_app_with_selective_rebuild
description: Counter demo app with selective rebuilds implemented with 'reduced' API and 'reduced_mobx' implementation as an example of the usage of the 'reduced_mobx' package.
publish_to: 'none' 
version: 0.3.0+3

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  reduced: 0.3.0
  reduced: 
    git:
      url: https://github.com/partmaster/reduced
      ref: v0.3.0
  reduced_mobx: 
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
